default:
  image: dockerhub.dsi.tecnico.ulisboa.pt/fenix-framework/docker/java-fenix-framework:jdk-17-node-18
  tags:
    - Maven
  before_script:
    - source ~/.bashrc

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  MAVEN_REPO_USER: $NEXUS_USERNAME
  MAVEN_REPO_PASS: $NEXUS_PASSWORD
  MAVEN_REPO_ID: dsi-maven-artifacts

stages:
  - Install and Lint
  - Release

Install and Lint:
  stage: Install and Lint
  # cache:
  #   paths:
  #     - .npm
  script:
    - mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true


Release:
  stage: Release
  script:
    - release.js $CI_PROJECT_ID $CI_COMMIT_TAG $REPO_API_ACCESS_TOKEN
    - mvn --batch-mode deploy  -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
    - notify-mattermost.js $CI_PROJECT_ID $CI_COMMIT_TAG $REPO_API_ACCESS_TOKEN $CHAT_HOOK
  only:
    - tags
