image: dockerhub.dsi.tecnico.ulisboa.pt/fenix-framework/docker/java-fenix-framework:jdk8

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - Install and Lint
  # - Test
  - Release
  - Notify

Install and Lint:
  stage: Install and Lint
  before_script:
    - cp -R /opt/config_m2 ./.m2
    - export MAVEN_REPO_USER=$NEXUS_USERNAME
    - export MAVEN_REPO_PASS=$NEXUS_PASSWORD
    - export MAVEN_REPO_ID=fenixedu-releases
  script:
    - mvn -s .m2/settings.xml clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true

# Test:
#   stage: Test
#   script:
#     - mvn test

Release:
  stage: Release
  before_script:
    - cp -R /opt/config_m2 ./.m2
    - export MAVEN_REPO_USER=$NEXUS_USERNAME
    - export MAVEN_REPO_PASS=$NEXUS_PASSWORD
    - export MAVEN_REPO_ID=fenixedu-releases
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@repo.dsi.tecnico.ulisboa.pt/tools/release-army-knife.git
    - cd release-army-knife
    - npm install
    - cd ..
    - mvn help:evaluate
    - VERSION=$(echo '${project.version}' | mvn help:evaluate | grep -v '^[[]')
    - if [[ v$VERSION != $CI_COMMIT_TAG ]]; then echo "Version v$VERSION in pom.xml diferent from $CI_COMMIT_TAG tag" && exit 1; fi
  script:
    - mvn -s .m2/settings.xml --batch-mode deploy  -Dmaven.test.skip=true  -Dmaven.javadoc.skip=true
    - node release-army-knife/release.js $CI_PROJECT_ID $CI_COMMIT_TAG $REPO_API_ACCESS_TOKEN
  only:
    - tags

Notify:
  stage: Notify
  before_script:
    - cp -R /opt/config_m2 ./.m2
    - export MAVEN_REPO_USER=$NEXUS_USERNAME
    - export MAVEN_REPO_PASS=$NEXUS_PASSWORD
    - export MAVEN_REPO_ID=fenixedu-releases
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@repo.dsi.tecnico.ulisboa.pt/tools/release-army-knife.git
    - cd release-army-knife
    - npm install
    - cd ..
    - mvn help:evaluate
    - VERSION=$(echo '${project.version}' | mvn help:evaluate | grep -v '^[[]')
    - if [[ v$VERSION != $CI_COMMIT_TAG ]]; then echo "Version v$VERSION in pom.xml diferent from $CI_COMMIT_TAG tag" && exit 1; fi
  script:
    - node release-army-knife/notify-mattermost.js $CI_PROJECT_ID $CI_COMMIT_TAG $REPO_API_ACCESS_TOKEN $CHAT_HOOK
  only:
    - tags